server:
  port: 9080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/12306?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:cn/train/mapper/*Mapper.xml
  type-aliases-package: cn.train.entity

#showSql
logging:
  level:
    cn:
      train:
        mapper: debug